//! `dark extend`: prepare an agent to keep writing this repository the way
//! it is already written.
//!
//! # The two halves, kept apart
//!
//! What this writes into `AGENTS.md` comes from two very different places,
//! and a reader must be able to tell which is which.
//!
//! The **facts** are counted: the language, the naming convention per kind
//! of definition, the documentation density, where the tests live, how
//! modules are named, the indentation. Every one comes from
//! `dark-explore`, is the same for a given commit, and can be checked
//! against the repository by anyone who doubts it.
//!
//! The **summary** is written by a model, from those facts plus the module
//! and hotspot lists — never from the repository itself, which would not
//! fit and would cost a minute. It is prose, it may be wrong, and it is
//! labelled as such where it lands.
//!
//! Blurring the two would be the failure mode: an agent that cannot tell a
//! counted convention from a guessed one applies both with equal
//! confidence.
//!
//! Nothing here opens a network connection.

use std::path::Path;

use anyhow::{Context as _, Result};
use dark_agentsmd::write::{Wrote, upsert};
use dark_explore::style::{Casing, Indent, ModuleLayout, StyleProfile, TestLayout};

use crate::explore::Report;
use crate::profile::{Mode, Profile};

/// How many modules and hotspots the summary prompt carries.
const NAMED_IN_PROMPT: usize = 12;

/// Below this agreement, a naming convention is a tendency rather than a
/// rule, and telling an agent to follow it would overstate the evidence.
const CONVENTION_THRESHOLD: f64 = 0.8;

/// Runs `dark extend`.
///
/// # Errors
///
/// Returns an error when no analysis exists, when the instruction file
/// cannot be written, or when the model call fails and `--no-summary` was
/// not given.
pub(crate) fn run_command(no_summary: bool) -> Result<()> {
    let root = crate::repo_root()?;
    let report = crate::plan::report_or_explain(&root)?;
    let style = crate::style::profile_for(&root)?;

    let summary = if no_summary {
        None
    } else {
        match summarise(&root, &report, &style) {
            Ok(text) => Some(text),
            Err(err) => {
                // A missing model must not cost the counted half. The
                // facts are the part an agent most needs, and they need
                // no model at all.
                println!("no summary: {err}");
                println!("the counted facts below are written anyway.\n");
                None
            }
        }
    };

    let body = render(&report, &style, summary.as_deref());
    let path = root.join("AGENTS.md");
    let wrote = upsert(&path, &body).map_err(crate::contract_error)?;

    Profile {
        mode: Mode::Extend,
        language: dominant_language(&report),
        target_language: None,
        pattern: None,
        tree_sha: report.tree_sha.clone(),
    }
    .write(&root)?;

    println!("{body}");
    println!();
    match wrote {
        Wrote::Created => println!("wrote {}", path.display()),
        Wrote::Replaced => println!("updated the generated section of {}", path.display()),
        Wrote::Unchanged => println!("{} already said this", path.display()),
    }
    println!("dark plan \"<idea>\" now charts with this repository's own context.");
    Ok(())
}

/// The language most of the repository is written in.
#[must_use]
pub(crate) fn dominant_language(report: &Report) -> Option<String> {
    report
        .languages
        .first()
        .map(|language| language.name.clone())
}

/// Renders the generated section.
#[must_use]
pub(crate) fn render(report: &Report, style: &StyleProfile, summary: Option<&str>) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();

    let _ = writeln!(
        out,
        "These notes are generated by `dark extend` from an analysis of this repository. \
         Everything under **Counted** was measured; anything under **Summary** was written \
         by a model and may be wrong."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Counted");
    let _ = writeln!(out);

    if let Some(language) = report.languages.first() {
        let mut line = format!(
            "- Language: {} ({} of {} files).",
            language.name, language.files, report.stats.files
        );
        let others: Vec<String> = report
            .languages
            .iter()
            .skip(1)
            .take(3)
            .map(|other| format!("{} ({})", other.name, other.files))
            .collect();
        if !others.is_empty() {
            let _ = write!(line, " Also present: {}.", others.join(", "));
        }
        let _ = writeln!(out, "{line}");
    }

    for convention in &style.conventions {
        if convention.agreement() < CONVENTION_THRESHOLD {
            continue;
        }
        let _ = writeln!(
            out,
            "- Name {} {} in {} ({:.0}% of {} do).",
            article(&convention.kind),
            convention.kind,
            casing_name(convention.casing),
            convention.agreement() * 100.0,
            convention.total,
        );
    }

    if style.exports > 0 {
        let _ = writeln!(
            out,
            "- {:.0}% of the {} exported definitions carry a doc comment.{}",
            style.doc_density() * 100.0,
            style.exports,
            if style.doc_density() >= 0.8 {
                " Write one for anything you export."
            } else {
                ""
            }
        );
    }

    let _ = writeln!(out, "- Tests: {}.", test_layout_text(style.test_layout));
    let _ = writeln!(
        out,
        "- Modules: {}.",
        module_layout_text(style.module_files)
    );

    if let Some(source) = style.source {
        if let Some(indent) = source.indent {
            let _ = writeln!(out, "- Indent with {}.", indent_text(indent));
        }
        let _ = writeln!(
            out,
            "- Lines run to about {} characters; files to about {} lines.",
            source.line_width_p95, source.file_lines_median
        );
    }

    if !report.seams.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "Respect these boundaries — they are where this repository already divides:"
        );
        for seam in report.seams.iter().take(5) {
            let _ = writeln!(out, "- `{}` to `{}`", seam.from, seam.to);
        }
    }

    if let Some(summary) = summary {
        let _ = writeln!(out);
        let _ = writeln!(out, "## Summary");
        let _ = writeln!(out);
        let _ = writeln!(out, "{}", summary.trim());
    }

    out
}

/// The indefinite article for a word.
///
/// Every definition kind this can be given starts with a consonant or a
/// vowel letter and none is an exception (no "a euro", no "an hour"), so
/// the letter decides it.
fn article(word: &str) -> &'static str {
    match word.chars().next() {
        Some('a' | 'e' | 'i' | 'o' | 'u') => "an",
        _ => "a",
    }
}

/// The word for a casing, written as an instruction rather than as an
/// enum variant.
const fn casing_name(casing: Casing) -> &'static str {
    match casing {
        Casing::Snake => "snake_case",
        Casing::Camel => "camelCase",
        Casing::Pascal => "PascalCase",
        Casing::ScreamingSnake => "SCREAMING_SNAKE_CASE",
        Casing::Kebab => "kebab-case",
        Casing::Flat => "one lower-case word",
        Casing::Other => "no consistent convention",
    }
}

/// What the test layout means, for a person or an agent to act on.
const fn test_layout_text(layout: TestLayout) -> &'static str {
    match layout {
        TestLayout::Alongside => "beside the code they test, in the same directory",
        TestLayout::Separate => "in their own directory",
        TestLayout::Mixed => "in both their own directory and beside the code",
        TestLayout::None => {
            "inside the files they test, with no separate test file — keep them there"
        }
    }
}

/// What the module layout means.
const fn module_layout_text(layout: ModuleLayout) -> &'static str {
    match layout {
        ModuleLayout::DirectoryFile => {
            "a directory holds the file that names it (`mod.rs`, `index.ts`)"
        }
        ModuleLayout::NamedFile => "named after the file, with no directory index file",
        ModuleLayout::Mixed => "named both ways; follow whichever the directory beside you uses",
    }
}

/// The indentation, written out.
fn indent_text(indent: Indent) -> String {
    match indent {
        Indent::Tab => "a tab".to_owned(),
        Indent::Spaces(1) => "one space".to_owned(),
        Indent::Spaces(n) => format!("{n} spaces"),
    }
}

// -------------------------------------------------------------- summary ---

/// Asks the model for a short description of what the repository does.
///
/// One call, bounded input. The repository itself is never sent: it would
/// not fit in an 18k context and reading it would cost minutes, and the
/// module and hotspot lists say more about a repository's shape than its
/// first few thousand lines do.
fn summarise(root: &Path, report: &Report, style: &StyleProfile) -> Result<String> {
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("could not start the summary runtime")?;
    runtime.block_on(summarise_async(root, report, style))
}

/// The prompt the summary is asked with.
///
/// Public to the crate so a test can assert on what is sent: the promise
/// that the repository's source is not in it is the kind that quietly
/// stops being true.
#[must_use]
pub(crate) fn summary_prompt(report: &Report, style: &StyleProfile) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();

    let _ = writeln!(
        out,
        "Describe what this repository is, in at most four sentences. \
         You are given counted facts about it, not its source. Do not invent \
         behaviour you were not told about. Do not repeat the numbers back."
    );
    let _ = writeln!(out);
    if let Some(language) = report.languages.first() {
        let _ = writeln!(out, "Language: {}", language.name);
    }
    let _ = writeln!(
        out,
        "Size: {} files, {} definitions",
        report.stats.files, report.stats.defs
    );
    let _ = writeln!(
        out,
        "Exports documented: {:.0}%",
        style.doc_density() * 100.0
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "Modules, largest first:");
    let mut modules: Vec<&crate::explore::ReportModule> = report.modules.iter().collect();
    modules.sort_by(|a, b| b.files.cmp(&a.files).then_with(|| a.path.cmp(&b.path)));
    for module in modules.iter().take(NAMED_IN_PROMPT) {
        let _ = writeln!(
            out,
            "  {} ({} files, {} depend on it)",
            module.path, module.files, module.ca
        );
    }
    if !report.hotspots.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "Most depended-on files:");
        for hotspot in report.hotspots.iter().take(NAMED_IN_PROMPT) {
            let _ = writeln!(out, "  {} ({} importers)", hotspot.path, hotspot.ca);
        }
    }
    out
}

/// Brings a session up and runs the one summary call.
async fn summarise_async(root: &Path, report: &Report, style: &StyleProfile) -> Result<String> {
    use dark_contract::{Chunk, Message, Request, Role, RoleClass};
    use futures_util::StreamExt as _;

    let bus = dark_contract::EventBus::new();
    let harness = crate::harness::bring_up(crate::harness::BringUp {
        root: root.to_path_buf(),
        dark_home: crate::dark_home(),
        preferred_model: None,
        policy: dark_core::policy::PolicyConfig::default(),
        mode: dark_core::policy::RunMode::Headless { yes: false },
        events: bus.tx(),
        tier_override: None,
    })
    .await?;

    let request = Request::new(
        RoleClass::Scout,
        vec![Message::text(Role::User, summary_prompt(report, style))],
    );
    let mut stream = harness
        .engine
        .stream(request, tokio_util::sync::CancellationToken::new())
        .await
        .map_err(crate::contract_error)?;

    let mut text = String::new();
    while let Some(chunk) = stream.next().await {
        if let Chunk::Text(delta) = chunk.map_err(crate::contract_error)? {
            text.push_str(&delta);
        }
    }
    Ok(text)
}

#[cfg(test)]
mod tests {
    use super::*;
    use dark_explore::style::{Convention, SourceShape};

    fn report() -> Report {
        serde_json::from_str(
            r#"{
              "tree_sha": "aa", "config_hash": "bb",
              "stats": {"files": 12, "defs": 90, "edges_f": 20, "edges_s": 140, "modularity": 0.5},
              "seams": [{"from": "a.rs", "to": "b.rs", "score": 0.7, "hard": true,
                "betweenness": 0.4, "crosses_community": true, "abstractness_target": 0.2,
                "cochange": 0.1, "test_proximity": 0.0}],
              "modules": [{"path": "src/core", "files": 7, "Ca": 4, "Ce": 1,
                "A": 0.2, "I": 0.2, "community": 0}],
              "hotspots": [{"path": "src/core/mod.rs", "Ca": 9}],
              "languages": [{"name": "Rust", "files": 11, "defs": 88},
                            {"name": "Python", "files": 1, "defs": 2}]
            }"#,
        )
        .expect("the fixture parses")
    }

    fn style() -> StyleProfile {
        StyleProfile {
            conventions: vec![
                Convention {
                    kind: "function".to_owned(),
                    casing: Casing::Snake,
                    agreeing: 95,
                    total: 100,
                },
                // Below the threshold: a tendency, not a rule.
                Convention {
                    kind: "variable".to_owned(),
                    casing: Casing::Camel,
                    agreeing: 6,
                    total: 10,
                },
            ],
            documented_exports: 88,
            exports: 90,
            test_layout: TestLayout::None,
            module_files: ModuleLayout::DirectoryFile,
            source: Some(SourceShape {
                indent: Some(Indent::Spaces(4)),
                line_width_p95: 96,
                file_lines_median: 180,
            }),
        }
    }

    #[test]
    fn the_dominant_language_leads() {
        assert_eq!(dominant_language(&report()), Some("Rust".to_owned()));
    }

    #[test]
    fn the_counted_half_names_the_language_and_the_conventions() {
        let text = render(&report(), &style(), None);
        assert!(text.contains("Language: Rust (11 of 12 files)"), "{text}");
        assert!(text.contains("snake_case"), "{text}");
        assert!(text.contains("Indent with 4 spaces"), "{text}");
        assert!(text.contains("96 characters"), "{text}");
    }

    #[test]
    fn a_kind_beginning_with_a_vowel_reads_correctly() {
        let mut style = style();
        style.conventions = vec![Convention {
            kind: "enum".to_owned(),
            casing: Casing::Pascal,
            agreeing: 10,
            total: 10,
        }];
        let text = render(&report(), &style, None);
        assert!(text.contains("Name an enum"), "{text}");
        assert!(!text.contains("Name a enum"), "{text}");
    }

    #[test]
    fn a_weak_majority_is_not_reported_as_a_rule() {
        // 60% is a tendency. Telling an agent to follow it would overstate
        // what the repository actually agrees on.
        let text = render(&report(), &style(), None);
        assert!(
            !text.contains("camelCase"),
            "a 60% majority must not become an instruction:\n{text}"
        );
    }

    #[test]
    fn the_two_halves_are_labelled() {
        let text = render(&report(), &style(), Some("It parses things."));
        assert!(text.contains("## Counted"), "{text}");
        assert!(text.contains("## Summary"), "{text}");
        assert!(
            text.contains("written by a model and may be wrong"),
            "a reader must be able to tell the halves apart:\n{text}"
        );
    }

    #[test]
    fn there_is_no_summary_heading_without_a_summary() {
        let text = render(&report(), &style(), None);
        assert!(!text.contains("## Summary"), "{text}");
        assert!(text.contains("## Counted"), "{text}");
    }

    #[test]
    fn the_seams_are_named_as_boundaries_to_respect() {
        let text = render(&report(), &style(), None);
        assert!(text.contains("`a.rs` to `b.rs`"), "{text}");
    }

    #[test]
    fn a_repository_that_tests_inside_its_files_is_told_to_keep_doing_that() {
        let text = render(&report(), &style(), None);
        assert!(text.contains("keep them there"), "{text}");
    }

    #[test]
    fn the_same_input_renders_identically() {
        assert_eq!(
            render(&report(), &style(), None),
            render(&report(), &style(), None)
        );
    }

    #[test]
    fn the_summary_prompt_never_carries_the_repository_itself() {
        // The promise the module documentation makes. It is the kind that
        // quietly stops being true when someone adds "a bit of context".
        let prompt = summary_prompt(&report(), &style());
        assert!(prompt.contains("src/core"), "the module list is sent");
        assert!(
            prompt.contains("not its source"),
            "the instruction must say so: {prompt}"
        );
        assert!(
            !prompt.contains("fn "),
            "no source code may reach the prompt:\n{prompt}"
        );
    }

    #[test]
    fn the_rendered_section_carries_no_markers_of_its_own() {
        // `dark_agentsmd::write::upsert` refuses a body containing one,
        // so this would fail at the write rather than corrupt the file —
        // but failing to write the notes at all is still a defect.
        let text = render(&report(), &style(), Some("Prose."));
        assert!(!text.contains(dark_agentsmd::write::BEGIN), "{text}");
        assert!(!text.contains(dark_agentsmd::write::END), "{text}");
    }
}
