//! `dark refactor`: choose a target language and an architecture, with the
//! reasoning shown.
//!
//! # Why every suggestion carries its evidence
//!
//! "Use microservices" is the kind of advice a tool can produce endlessly
//! and nobody can check. Discovery already computes the numbers architects
//! actually reason from — Louvain modularity, community sizes, bridge
//! edges, and Martin's coupling metrics per module — so a suggestion here
//! is a lookup against those numbers with the numbers printed beside it.
//!
//! A person who disagrees can see exactly which figure produced the advice
//! and overrule it. A suggestion nobody can check is worse than none.
//!
//! # What this is not
//!
//! Graph metrics describe the code as written. They know nothing about the
//! product, the team, the deadline, or the operational appetite for
//! running twelve services. The output says so, every time, because a
//! confident-sounding recommendation from a tool carries more weight than
//! it has earned.

use anyhow::Result;
use dark_explore::syntax::Language;

use crate::explore::{Report, ReportModule};
use crate::profile::{Mode, Profile};

/// Runs `dark refactor`.
///
/// # Errors
///
/// Returns an error when no analysis exists, when the target language is
/// not one the harness can parse, when a named pattern is unknown, or when
/// the instruction file cannot be written.
pub(crate) fn run_command(to: Option<&str>, pattern: Option<&str>, dark: bool) -> Result<()> {
    let root = crate::repo_root()?;
    let report = crate::plan::report_or_explain(&root)?;
    let current = crate::extend::dominant_language(&report);
    let target = resolve_target(to, current.as_deref())?;

    let suggestion = match pattern {
        Some(name) => {
            let chosen = parse_pattern(name)?;
            Suggestion {
                pattern: chosen,
                evidence: vec!["chosen on the command line".to_owned()],
                because: "you named this rather than taking the suggestion.",
            }
        }
        None => suggest(&report),
    };

    print!("{}", render(&report, &suggestion, &target));

    let table = crate::docsource::DocTable::load(&crate::dark_home())?;
    let sources = table.for_target(&target, suggestion.pattern);
    println!();
    print!("{}", crate::docsource::render(&sources, dark));

    let body = notes(&report, &suggestion, &target, current.as_deref());
    let path = root.join("AGENTS.md");
    let wrote = dark_agentsmd::write::upsert(&path, &body).map_err(crate::contract_error)?;

    Profile {
        mode: Mode::Refactor,
        language: current,
        target_language: Some(target.clone()),
        pattern: Some(suggestion.pattern.name().to_owned()),
        tree_sha: report.tree_sha.clone(),
    }
    .write(&root)?;

    println!();
    match wrote {
        dark_agentsmd::write::Wrote::Created => println!("wrote {}", path.display()),
        dark_agentsmd::write::Wrote::Replaced => {
            println!("updated the generated section of {}", path.display());
        }
        dark_agentsmd::write::Wrote::Unchanged => println!("{} already said this", path.display()),
    }
    println!("dark plan \"<idea>\" now charts towards this target.");
    Ok(())
}

/// Renders the generated section a refactor writes.
///
/// Unlike `dark extend`'s, this describes where the repository is going
/// rather than where it is — an agent told to match the present would
/// undo the refactor it was asked to make. It says both, so the agent
/// knows which code it is reading and which it is writing.
#[must_use]
pub(crate) fn notes(
    report: &Report,
    suggestion: &Suggestion,
    target: &str,
    current: Option<&str>,
) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();

    let _ = writeln!(
        out,
        "These notes are generated by `dark refactor`. This repository is being taken \
         somewhere, so the code you read and the code you write are not the same."
    );
    let _ = writeln!(out);
    let _ = writeln!(out, "## Target");
    let _ = writeln!(out);
    let _ = writeln!(out, "- Write {target}.");
    if let Some(current) = current
        && current != target
    {
        let _ = writeln!(
            out,
            "- The existing code is {current}. Read it for behaviour, not for style."
        );
    }
    let _ = writeln!(out, "- Architecture: {}.", suggestion.pattern.name());
    let _ = writeln!(out, "- {}", suggestion.because);
    let _ = writeln!(out);
    let _ = writeln!(out, "## Evidence");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "The pattern above was read off the dependency graph, from:"
    );
    for line in &suggestion.evidence {
        let _ = writeln!(out, "- {line}");
    }

    if !report.seams.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "These are the boundaries it found. A split that follows them moves less code \
             than one that does not:"
        );
        for seam in report.seams.iter().take(5) {
            let _ = writeln!(out, "- `{}` to `{}`", seam.from, seam.to);
        }
    }
    out
}

/// A modularity above this means the graph already divides cleanly.
const HIGH_MODULARITY: f64 = 0.4;

/// An afferent coupling above this share of all modules marks a module
/// everything depends on.
const GOD_MODULE_SHARE: f64 = 0.4;

/// Above this, a module is abstract enough that its seams are interfaces.
const HIGH_ABSTRACTNESS: f64 = 0.5;

/// Above this, a module depends outward more than it is depended on.
const HIGH_INSTABILITY: f64 = 0.7;

/// A repository below this size has nothing to gain from being split.
const SMALL_REPOSITORY: u32 = 25;

/// An architectural pattern the analysis can argue for.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Pattern {
    /// Split along the community boundaries that already exist.
    ServiceSplit,
    /// Put a layer or a port-and-adapter boundary in first.
    Layered,
    /// Replace a many-to-many mesh with a bus.
    EventDriven,
    /// Formalise the interfaces that are already there.
    Plugin,
    /// Leave the shape alone.
    KeepMonolith,
}

impl Pattern {
    /// The name written into the profile and shown to a person.
    pub(crate) const fn name(self) -> &'static str {
        match self {
            Self::ServiceSplit => "service split",
            Self::Layered => "layered or hexagonal",
            Self::EventDriven => "event-driven",
            Self::Plugin => "plugin architecture",
            Self::KeepMonolith => "keep the monolith",
        }
    }
}

/// A suggestion, and the measurement behind it.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct Suggestion {
    /// What to do.
    pub(crate) pattern: Pattern,
    /// The numbers that produced it, each written so a person can check it
    /// against the analysis themselves.
    pub(crate) evidence: Vec<String>,
    /// Why those numbers point that way.
    pub(crate) because: &'static str,
}

/// Chooses a pattern for `report`.
///
/// The rules are ordered by how much weight the evidence carries, and the
/// first that fires wins. A god-module outranks a high modularity because
/// distributing a repository that has one distributes the problem rather
/// than solving it — the order is the argument, not an implementation
/// detail.
#[must_use]
pub(crate) fn suggest(report: &Report) -> Suggestion {
    if report.stats.files < SMALL_REPOSITORY {
        return Suggestion {
            pattern: Pattern::KeepMonolith,
            evidence: vec![format!("{} files", report.stats.files)],
            because: "there is not enough here for a split to pay for itself. Saying so is \
                      more useful than a recommendation.",
        };
    }

    if let Some(module) = god_module(report) {
        return Suggestion {
            pattern: Pattern::Layered,
            evidence: vec![
                format!(
                    "{} of {} modules depend on {}",
                    module.ca,
                    report.modules.len(),
                    module.path
                ),
                format!("modularity {:.2}", report.stats.modularity),
            ],
            because: "one module holds everything together. Distributing a repository shaped \
                      like this distributes the problem; put a boundary inside it first.",
        };
    }

    if report.stats.modularity > HIGH_MODULARITY {
        let communities = community_count(report);
        return Suggestion {
            pattern: Pattern::ServiceSplit,
            evidence: vec![
                format!("modularity {:.2}", report.stats.modularity),
                format!("{communities} communities"),
                format!("{} hard boundaries", hard_seams(report)),
            ],
            because: "the cut lines already exist. The graph is telling you where they are, \
                      and a split along them moves less code than one you choose yourself.",
        };
    }

    let interfaces = interface_modules(report);
    if interfaces >= 2 {
        return Suggestion {
            pattern: Pattern::Plugin,
            evidence: vec![format!(
                "{interfaces} modules are both abstract (A > {HIGH_ABSTRACTNESS}) and unstable \
                 (I > {HIGH_INSTABILITY})"
            )],
            because: "those seams are already interfaces. Formalising them costs less than \
                      inventing new ones.",
        };
    }

    Suggestion {
        pattern: Pattern::EventDriven,
        evidence: vec![
            format!("modularity {:.2}", report.stats.modularity),
            format!("average efferent coupling {:.1}", average_ce(report)),
        ],
        because: "the coupling is many-to-many and no clean boundary stands out. A bus \
                  removes the mesh rather than re-drawing it.",
    }
}

/// The module everything depends on, when one stands out that far.
fn god_module(report: &Report) -> Option<&ReportModule> {
    let total = u32::try_from(report.modules.len()).unwrap_or(u32::MAX);
    if total < 3 {
        return None;
    }
    let threshold = f64::from(total) * GOD_MODULE_SHARE;
    report
        .modules
        .iter()
        .filter(|module| f64::from(module.ca) > threshold)
        .max_by_key(|module| module.ca)
}

/// How many communities the modules fall into.
fn community_count(report: &Report) -> usize {
    report
        .modules
        .iter()
        .map(|module| module.community)
        .collect::<std::collections::BTreeSet<_>>()
        .len()
}

/// How many of the reported seams are bridges.
fn hard_seams(report: &Report) -> usize {
    report.seams.iter().filter(|seam| seam.hard).count()
}

/// How many modules are abstract and unstable at once.
fn interface_modules(report: &Report) -> usize {
    report
        .modules
        .iter()
        .filter(|module| module.a > HIGH_ABSTRACTNESS && module.i > HIGH_INSTABILITY)
        .count()
}

/// The mean efferent coupling across the modules.
#[allow(
    clippy::cast_precision_loss,
    reason = "a module count is far inside f64's exact integer range; a repository with more \
              modules than that has other problems"
)]
fn average_ce(report: &Report) -> f64 {
    if report.modules.is_empty() {
        return 0.0;
    }
    let total: u32 = report.modules.iter().map(|module| module.ce).sum();
    f64::from(total) / report.modules.len() as f64
}

/// Renders the suggestion for a person to read, or to disagree with.
#[must_use]
pub(crate) fn render(report: &Report, suggestion: &Suggestion, target: &str) -> String {
    use std::fmt::Write as _;
    let mut out = String::new();

    let _ = writeln!(out, "target language: {target}");
    let _ = writeln!(out, "suggested pattern: {}", suggestion.pattern.name());
    let _ = writeln!(out);
    let _ = writeln!(out, "from the analysis:");
    for line in &suggestion.evidence {
        let _ = writeln!(out, "  {line}");
    }
    let _ = writeln!(out);
    let _ = writeln!(out, "{}", suggestion.because);
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "This is read off the dependency graph. It knows nothing about your product, your \
         team, or how many services you want to run. Overrule it with --pattern."
    );

    if !report.seams.is_empty() {
        let _ = writeln!(out);
        let _ = writeln!(out, "the boundaries it is reasoning from:");
        for seam in report.seams.iter().take(5) {
            let _ = writeln!(
                out,
                "  {} to {} ({:.2}{})",
                seam.from,
                seam.to,
                seam.score,
                if seam.hard { ", a bridge" } else { "" }
            );
        }
    }
    out
}

/// Resolves the requested target language against the grammars the
/// harness can parse.
///
/// A target outside that set means the harness cannot analyse what it
/// helped build — no seams, no blast radius, no style profile — so it is
/// refused here rather than discovered later.
///
/// # Errors
///
/// Returns an error naming every supported language when `requested` is
/// not one of them.
pub(crate) fn resolve_target(
    requested: Option<&str>,
    current: Option<&str>,
) -> anyhow::Result<String> {
    let Some(requested) = requested else {
        return current.map(str::to_owned).ok_or_else(|| {
            anyhow::anyhow!(
                "this repository's language could not be determined, so there is no default \
                 target. Name one with --to: {}",
                supported().join(", ")
            )
        });
    };

    Language::ALL
        .iter()
        .find(|language| language.name().eq_ignore_ascii_case(requested))
        .map(|language| language.name().to_owned())
        .ok_or_else(|| {
            anyhow::anyhow!(
                "darkharness cannot parse {requested}, so it could not analyse the result. \
                 Supported: {}",
                supported().join(", ")
            )
        })
}

/// Every language the syntax stage parses.
fn supported() -> Vec<&'static str> {
    Language::ALL.iter().map(|l| l.name()).collect()
}

/// Reads a pattern named on the command line.
///
/// # Errors
///
/// Returns an error naming every pattern when `name` is not one of them.
pub(crate) fn parse_pattern(name: &str) -> anyhow::Result<Pattern> {
    const ALL: [Pattern; 5] = [
        Pattern::ServiceSplit,
        Pattern::Layered,
        Pattern::EventDriven,
        Pattern::Plugin,
        Pattern::KeepMonolith,
    ];
    let wanted = name.trim().to_lowercase();
    ALL.iter()
        .find(|pattern| pattern.name() == wanted)
        .copied()
        .ok_or_else(|| {
            anyhow::anyhow!(
                "{name} is not a pattern. One of: {}",
                ALL.iter()
                    .map(|p| format!("\"{}\"", p.name()))
                    .collect::<Vec<_>>()
                    .join(", ")
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn report(files: u32, modularity: f64, modules: &str, seams: &str) -> Report {
        serde_json::from_str(&format!(
            r#"{{
              "tree_sha": "aa", "config_hash": "bb",
              "stats": {{"files": {files}, "defs": 900, "edges_f": 200,
                         "edges_s": 1400, "modularity": {modularity}}},
              "seams": [{seams}],
              "modules": [{modules}],
              "hotspots": [],
              "languages": [{{"name": "Rust", "files": {files}, "defs": 900}}]
            }}"#
        ))
        .expect("the fixture parses")
    }

    fn module(path: &str, ca: u32, ce: u32, a: f64, i: f64, community: u32) -> String {
        format!(
            r#"{{"path": "{path}", "files": 5, "Ca": {ca}, "Ce": {ce},
                 "A": {a}, "I": {i}, "community": {community}}}"#
        )
    }

    fn seam(hard: bool) -> String {
        format!(
            r#"{{"from": "a.rs", "to": "b.rs", "score": 0.7, "hard": {hard},
                 "betweenness": 0.4, "crosses_community": true,
                 "abstractness_target": 0.2, "cochange": 0.1, "test_proximity": 0.0}}"#
        )
    }

    #[test]
    fn a_small_repository_is_told_to_stay_one_thing() {
        let suggestion = suggest(&report(
            8,
            0.9,
            &module("src/a", 1, 1, 0.1, 0.1, 0),
            &seam(true),
        ));
        assert_eq!(suggestion.pattern, Pattern::KeepMonolith);
        assert!(suggestion.evidence[0].contains("8 files"));
    }

    #[test]
    fn a_god_module_outranks_a_high_modularity() {
        // This ordering is the argument, not an accident: a repository
        // with one module everything depends on gets no benefit from
        // being distributed until that module is broken up.
        let modules = [
            module("src/core", 8, 1, 0.2, 0.2, 0),
            module("src/a", 0, 3, 0.2, 0.9, 1),
            module("src/b", 0, 3, 0.2, 0.9, 2),
            module("src/c", 0, 3, 0.2, 0.9, 3),
            module("src/d", 0, 3, 0.2, 0.9, 4),
        ]
        .join(",");
        let suggestion = suggest(&report(200, 0.72, &modules, &seam(true)));
        assert_eq!(suggestion.pattern, Pattern::Layered);
        assert!(
            suggestion.evidence.iter().any(|e| e.contains("src/core")),
            "the evidence must name the module: {:?}",
            suggestion.evidence
        );
    }

    #[test]
    fn a_cleanly_divided_repository_is_offered_a_service_split() {
        let modules = [
            module("src/a", 1, 1, 0.2, 0.3, 0),
            module("src/b", 1, 1, 0.2, 0.3, 1),
            module("src/c", 1, 1, 0.2, 0.3, 2),
            module("src/d", 1, 1, 0.2, 0.3, 3),
        ]
        .join(",");
        let suggestion = suggest(&report(200, 0.61, &modules, &seam(true)));
        assert_eq!(suggestion.pattern, Pattern::ServiceSplit);
        assert!(
            suggestion
                .evidence
                .iter()
                .any(|e| e.contains("4 communities")),
            "{:?}",
            suggestion.evidence
        );
    }

    #[test]
    fn abstract_unstable_modules_suggest_formalising_the_interfaces() {
        let modules = [
            module("src/a", 1, 4, 0.8, 0.9, 0),
            module("src/b", 1, 4, 0.8, 0.9, 0),
            module("src/c", 1, 4, 0.1, 0.2, 0),
            module("src/d", 1, 4, 0.1, 0.2, 0),
        ]
        .join(",");
        let suggestion = suggest(&report(200, 0.2, &modules, &seam(false)));
        assert_eq!(suggestion.pattern, Pattern::Plugin);
    }

    #[test]
    fn a_tangled_repository_falls_through_to_a_bus() {
        let modules = [
            module("src/a", 1, 6, 0.1, 0.4, 0),
            module("src/b", 1, 6, 0.1, 0.4, 0),
            module("src/c", 1, 6, 0.1, 0.4, 0),
            module("src/d", 1, 6, 0.1, 0.4, 0),
        ]
        .join(",");
        let suggestion = suggest(&report(200, 0.15, &modules, &seam(false)));
        assert_eq!(suggestion.pattern, Pattern::EventDriven);
    }

    #[test]
    fn every_suggestion_carries_at_least_one_measurement() {
        // The rule the module exists for: advice nobody can check is
        // worse than no advice.
        let cases = [
            report(8, 0.9, &module("src/a", 1, 1, 0.1, 0.1, 0), &seam(true)),
            report(
                200,
                0.61,
                &[
                    module("src/a", 1, 1, 0.2, 0.3, 0),
                    module("src/b", 1, 1, 0.2, 0.3, 1),
                    module("src/c", 1, 1, 0.2, 0.3, 2),
                ]
                .join(","),
                &seam(true),
            ),
            report(
                200,
                0.15,
                &[
                    module("src/a", 1, 6, 0.1, 0.4, 0),
                    module("src/b", 1, 6, 0.1, 0.4, 0),
                    module("src/c", 1, 6, 0.1, 0.4, 0),
                ]
                .join(","),
                &seam(false),
            ),
        ];
        for case in cases {
            let suggestion = suggest(&case);
            assert!(
                !suggestion.evidence.is_empty(),
                "{:?} arrived with no evidence",
                suggestion.pattern
            );
        }
    }

    #[test]
    fn the_rendered_advice_says_what_it_does_not_know() {
        let case = report(200, 0.61, &module("src/a", 1, 1, 0.2, 0.3, 0), &seam(true));
        let text = render(&case, &suggest(&case), "Rust");
        assert!(text.contains("knows nothing about your product"), "{text}");
        assert!(text.contains("Overrule it"), "{text}");
    }

    #[test]
    fn an_unsupported_target_is_refused_with_the_list() {
        let err = resolve_target(Some("COBOL"), Some("Rust"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("cannot parse COBOL"), "{err}");
        assert!(err.contains("rust"), "the list must be shown: {err}");
    }

    #[test]
    fn a_supported_target_is_accepted_whatever_its_case() {
        // `Language::name` is the canonical spelling, and it is lower
        // case; a target typed either way resolves to it.
        assert_eq!(resolve_target(Some("Rust"), None).unwrap(), "rust");
        assert_eq!(resolve_target(Some("go"), None).unwrap(), "go");
    }

    #[test]
    fn no_target_keeps_the_current_language() {
        assert_eq!(resolve_target(None, Some("Python")).unwrap(), "Python");
    }

    #[test]
    fn no_target_and_no_current_language_asks_for_one() {
        let err = resolve_target(None, None).unwrap_err().to_string();
        assert!(err.contains("--to"), "{err}");
    }

    #[test]
    fn a_pattern_can_be_named_on_the_command_line() {
        assert_eq!(
            parse_pattern("service split").unwrap(),
            Pattern::ServiceSplit
        );
        // Case and surrounding space do not matter; the words do.
        assert_eq!(
            parse_pattern("  Event-Driven ").unwrap(),
            Pattern::EventDriven
        );
    }

    #[test]
    fn an_unknown_pattern_lists_the_real_ones() {
        let err = parse_pattern("microservices").unwrap_err().to_string();
        assert!(err.contains("service split"), "{err}");
    }
}
