[package]
name = "dark-airlock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "The only HTTP client in the workspace."

[dependencies]
dark-contract.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync", "time"] }
tracing.workspace = true
url.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
