[package]
name = "dark-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "The full-screen terminal application."

[dependencies]
crossterm = "0.29.0"
dark-contract.workspace = true
ratatui = "0.29.0"

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
